### ISSUE TITLE
Training problem

### ISSUE THREAD

**Issue by Monoclinic** [xqlin98/INSTINCT#2]
Hello I tried the Induction training but there are some problems.
Take task "antonyms" as an example.
First, it's possible that the model would not get a good prompt after 165 iters. It seems that the generated prompt has never been closed to "antonym" or similar words. Instead, irrelevant prompts are provided all the time.
Second, sometimes you can get a somehow good result, but it's a few-shot example, not a good Induction.

`Instruction: ['The instruction was to take a nap\nInput: unstack\nOutput: stack\nInput: unstack\nOutput: stack\nInput: unstack\nOutput: stack\nInput: unstack\nOutput: stack\nInput: unstack\nOutput: stack\nInput: unstack\nOutput: stack\nInput: unstack\nOutput']`

And my training loss is extremely low, which is strange. I wonder if there are some bugs.
```
Start training...
Training Loss :  5.357048022363033e-08
iter 107 --- reward: 0.0
Best value found till now: 0.95
Start selecting...
Instruction: ['The instruction was to cook the dinner, which was a dish of some sort']
gpt-3.5-turbo-0301
```

**Comment by xqlin98** [comment]
Hi Monoclinic,

> First, it's possible that the model would not get a good prompt after 165 iters.

Yes, it is possible that after 165 iterations, INSTINCT might not be able to always give a good result. That's why in our paper, INSTINCT sometimes performs not so well on some tasks. But overall, INSTINCT performs the best among the 30 tasks.

> sometimes you can get a somehow good result, but it's a few-shot example, not a good Induction.

We do notice that sometimes the instruction provided by INSTINCT is the few-shot example and we have discussed this phenomenon in the appendix of our paper. In the zero-shot in-context learning case, an instruction with few-shot examples can be a good one. 

> my training loss is extremely low

The training loss is expected to be low, since NN is used to train on a dataset with less than 165 data points. If you want a not-so-low training loss, you can increase the lambda parameter in our script.

Please make sure the Vicuna you are using is 1.1. Let me know if you have further questions. Thanks!

Best,
Xiaoqiang

**Comment by Monoclinic** [comment]
Hi Xiaoqiang,
Many thanks for your reply!

> Please make sure the Vicuna you are using is 1.1

I'm using Vicuna-7B-v1.5 and maybe that's the reason. I'll have a try with 13B-v1.1.
